/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package projek_uas;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.Arrays;

/**
 *
 * @author VivoBook
 */
public class LoginApotek extends javax.swing.JDialog {

    private Component formPanel;
    
    /**
     * Creates new form ApotekApp
     */
    public LoginApotek(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        UserLabel = new javax.swing.JLabel();
        PassLabel = new javax.swing.JLabel();
        UserField = new javax.swing.JTextField();
        PassField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        LoginLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserLabel.setText("Username");
        LoginPanel.add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        PassLabel.setText("Password");
        LoginPanel.add(PassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));
        LoginPanel.add(UserField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 210, -1));
        LoginPanel.add(PassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 210, -1));

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        LoginPanel.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 80, -1));

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        LoginPanel.add(ClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 80, -1));

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        LoginPanel.add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 80, -1));

        LoginLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginLabel.setText("Silahkan Login");
        LoginPanel.add(LoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 170, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\A New Download\\newapotek.jpg")); // NOI18N
        LoginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 120, 90));

        getContentPane().add(LoginPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        UserField.setText("");
        PassField.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        String username = UserField.getText();
                char[] passwordChars = PassField.getPassword();
                String password = new String(passwordChars);

                // Buat koneksi ke database
                String jdbcURL = "jdbc:mysql://localhost:3306/db_apotek"; 
                String dbUsername = "root"; 
                String dbPassword = ""; 

                try {
                    Connection connection = DriverManager.getConnection(jdbcURL, dbUsername, dbPassword);

                    // Buat statement SQL
                    String query = "SELECT * FROM login WHERE username=? AND password=?";
                    PreparedStatement preparedStatement = connection.prepareStatement(query);
                    preparedStatement.setString(1, username);
                    preparedStatement.setString(2, password);

                    // Eksekusi query
                    ResultSet resultSet = preparedStatement.executeQuery();

                    // Periksa hasil query
                    if (resultSet.next()) {
                        resultSet.close();
                        preparedStatement.close();
                        connection.close();
                        Arrays.fill(passwordChars, '0');
                        PassField.setText("");
                        dispose();
                        NewApotek.main(null);

                    } else {
                        // Component formPanel = null;
                        JOptionPane.showMessageDialog(formPanel, "Login Gagal. Silakan coba lagi.");
                    }

                    // Tutup koneksi ke database
                    resultSet.close();
                    preparedStatement.close();
                    connection.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    // Component formPanel = null;
                    JOptionPane.showMessageDialog(formPanel, "Kesalahan Koneksi Database.");
                }

                // Hapus kata sandi dari memori dan hapus isi dari password field
                Arrays.fill(passwordChars, '0');
                PassField.setText(""); 
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginApotek dialog = new LoginApotek(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JTextField UserField;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
